/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package core.GUI;
import core.Library.Item;
import javax.swing.JOptionPane;

/**
 *
 * @author krest
 */
public class addItem extends javax.swing.JFrame
{
    
    DataAccessor.MySQLAccessor accessor;
    boolean toEdit = false;


    /**
     * Creates new form addItem
     * @param add
     */
    public addItem(boolean edit, Item item)
    {
        initComponents();
        accessor = new DataAccessor.MySQLAccessor();
        if (edit){
            toEdit = true;
            addButton.setText("Save");
            itemIdTextField2.setText(item.getId());
            itemIdTextField2.setEditable(false);
            titleTextField.setText(item.getTitle());
            switch(item.getItemType()){
                case Book:
                    itemTypeComboBox.setSelectedIndex(0);
                    break;
                case DVD:
                    itemTypeComboBox.setSelectedIndex(1);
                    break;
                case Magazine:
                    itemTypeComboBox.setSelectedIndex(2);
                    break;
                default:
                    itemTypeComboBox.setSelectedIndex(0);
                    break;
            }
            creatorTextField.setText(item.getCreator());
        }

    }
    
    
    
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        itemIdTextField2 = new javax.swing.JTextField();
        titleTextField = new javax.swing.JTextField();
        creatorTextField = new javax.swing.JTextField();
        itemTypeComboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        rentalDaysLabel = new javax.swing.JLabel();
        backButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 51));
        jLabel6.setText("Fill the text fields to add a new Item.");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Item ID: ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Title: ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Item Type: ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Creator");

        addButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addButton.setText("Add");
        addButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                addButtonActionPerformed(evt);
            }
        });

        itemTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Book", "DVD", "Magazine" }));
        itemTypeComboBox.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                itemTypeComboBoxActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Rental Days:");

        rentalDaysLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rentalDaysLabel.setText("21");

        backButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backButton6.setText("Back");
        backButton6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backButton6.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                backButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(itemIdTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                                    .addComponent(titleTextField)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(itemTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(77, 77, 77)
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(rentalDaysLabel))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                                .addComponent(creatorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(64, 64, 64))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(itemIdTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(titleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(itemTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(rentalDaysLabel))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(creatorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(addButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(backButton6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_addButtonActionPerformed
    {//GEN-HEADEREND:event_addButtonActionPerformed
        // TODO add your handling code here:
       
        Item item = new Item();
        
        String itemId = itemIdTextField2.getText();
        String title = titleTextField.getText();
        String creator = creatorTextField.getText();
        if (itemId.isEmpty())
        { 
            JOptionPane.showMessageDialog(null, "Please Enter a Valid Item Id.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (title.isEmpty())
        { 
            JOptionPane.showMessageDialog(null, "Please Enter a Valid Title.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (creator.isEmpty())
        { 
            JOptionPane.showMessageDialog(null, "Please Enter a Valid Creator.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        item.setId(itemId);
        item.setTitle(title);
        item.setItemType(getItemType());
        item.setCreator(creator);
        item.setRentalDays(getRentalDaysForIndex(itemTypeComboBox.getSelectedIndex()));
       
        if (toEdit){
            accessor.editItem(item);
            JOptionPane.showMessageDialog(null, "The item successfully saved!", "Alert", JOptionPane.INFORMATION_MESSAGE);
        }else{//Adding
            accessor.AddItem(item);
            JOptionPane.showMessageDialog(null, "The item is successfully added!", "Alert", JOptionPane.INFORMATION_MESSAGE);
        }
        
         //empty textfields
        itemIdTextField2.setText(" ");
        titleTextField.setText(" ");
        creatorTextField.setText(" ");

    }//GEN-LAST:event_addButtonActionPerformed

    private String getRentalDaysForIndex(int index){
        switch (index){
            case 0:
                return "21";
            case 1:
               return "7";
            case 2:
                return "7";
            default:
                return "21";
        }
    }
    
    private void itemTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_itemTypeComboBoxActionPerformed
    {//GEN-HEADEREND:event_itemTypeComboBoxActionPerformed
        // TODO add your handling code here:
        rentalDaysLabel.setText(getRentalDaysForIndex(itemTypeComboBox.getSelectedIndex()));
    }//GEN-LAST:event_itemTypeComboBoxActionPerformed

    private void backButton6ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_backButton6ActionPerformed
    {//GEN-HEADEREND:event_backButton6ActionPerformed
        this.dispose();
        new Services().setVisible(true);
    }//GEN-LAST:event_backButton6ActionPerformed

    
    public Item.ItemType getItemType(){
        switch (itemTypeComboBox.getSelectedIndex()){
            case 0:
                return Item.ItemType.Book;
            case 1:
                return Item.ItemType.DVD;
            case 2:
                return Item.ItemType.Magazine;
            default:
                return Item.ItemType.Book; //book because this is most common
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(addItem.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(addItem.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(addItem.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(addItem.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new addItem(false, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton backButton6;
    private javax.swing.JTextField creatorTextField;
    private javax.swing.JTextField itemIdTextField2;
    private javax.swing.JComboBox<String> itemTypeComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel rentalDaysLabel;
    private javax.swing.JTextField titleTextField;
    // End of variables declaration//GEN-END:variables
}
