/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package core.GUI;

import core.Library.Librarian;
import javax.swing.JOptionPane;

/**
 *
 * @author krest
 */
public class addLibrarian extends javax.swing.JFrame
{
    DataAccessor.MySQLAccessor accessor;
    boolean toEdit = false;

    /**
     * Creates new form addLibrarian
     */
    public addLibrarian(boolean edit, Librarian librarian)
    {
        initComponents();
        accessor = new DataAccessor.MySQLAccessor();
        if (edit){
            toEdit = true;
            addLibrarianButton.setText("Save");
            librarianIdTextField.setText(librarian.getId());
            librarianIdTextField.setEditable(false);
            passwordTextField.setText(librarian.getPassword());
            librarianNameTextField.setText(librarian.getName());
            librarianAddressTextField.setText(librarian.getAddress());
            librarianPhoneNumTextField.setText(librarian.getPhoneNum());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        librarianIdTextField = new javax.swing.JTextField();
        passwordTextField = new javax.swing.JTextField();
        librarianNameTextField = new javax.swing.JTextField();
        librarianAddressTextField = new javax.swing.JTextField();
        librarianPhoneNumTextField = new javax.swing.JTextField();
        backButton6 = new javax.swing.JButton();
        addLibrarianButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 51));
        jLabel6.setText("Fill the text fields to add a new Item.");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Librarian ID: ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Password: ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Name: ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Address: ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Phone Number: ");

        backButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backButton6.setText("Back");
        backButton6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backButton6.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                backButton6ActionPerformed(evt);
            }
        });

        addLibrarianButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addLibrarianButton.setText("Add");
        addLibrarianButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addLibrarianButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                addLibrarianButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(librarianIdTextField)
                            .addComponent(passwordTextField)
                            .addComponent(librarianNameTextField)
                            .addComponent(librarianAddressTextField)
                            .addComponent(librarianPhoneNumTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(addLibrarianButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(librarianIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(librarianNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(librarianAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(librarianPhoneNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(addLibrarianButton)
                .addGap(41, 41, 41)
                .addComponent(backButton6)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButton6ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_backButton6ActionPerformed
    {//GEN-HEADEREND:event_backButton6ActionPerformed
        this.dispose();
        new Services().setVisible(true);
    }//GEN-LAST:event_backButton6ActionPerformed

    private void addLibrarianButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_addLibrarianButtonActionPerformed
    {//GEN-HEADEREND:event_addLibrarianButtonActionPerformed
        //fetch all form input
        Librarian librarian = new Librarian();
        
        String librarianId = librarianIdTextField.getText();
        String password = passwordTextField.getText();
        String name = librarianNameTextField.getText();
        String address = librarianAddressTextField.getText();
        String phoneNum = librarianPhoneNumTextField.getText();
        
        if (librarianId.isEmpty())
        { 
            JOptionPane.showMessageDialog(null, "Please Enter a Valid Librarian Id.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (password.isEmpty())
        { 
            JOptionPane.showMessageDialog(null, "Please Enter a Valid Password.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (name.isEmpty())
        { 
            JOptionPane.showMessageDialog(null, "Please Enter a Valid Name.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (address.isEmpty())
        { 
            JOptionPane.showMessageDialog(null, "Please Enter a Valid Item Address", "Invalid Input", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (phoneNum.isEmpty())
        { 
            JOptionPane.showMessageDialog(null, "Please Enter a Valid Phone Number", "Invalid Input", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        librarian.setId(librarianId);
        librarian.setPassword(password);
        librarian.setName(name);
        librarian.setAddress(address);
        librarian.setPhoneNum(phoneNum);
       
        //adds librarian to db
        if (toEdit){
            accessor.editLibrarian(librarian);
            JOptionPane.showMessageDialog(null, "The changes to librarian successfully saved!", "Alert", JOptionPane.INFORMATION_MESSAGE);
        }else{//Adding
            accessor.AddLibrarian(librarian);
            JOptionPane.showMessageDialog(null, "The librarian is successfully added!", "Alert", JOptionPane.INFORMATION_MESSAGE);
        }
        
        //empty textfields
        librarianIdTextField.setText(" ");
        passwordTextField.setText(" ");
        librarianNameTextField.setText(" ");
        librarianAddressTextField.setText(" ");
        librarianPhoneNumTextField.setText(" ");
        
    }//GEN-LAST:event_addLibrarianButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(addLibrarian.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(addLibrarian.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(addLibrarian.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(addLibrarian.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new addLibrarian(false, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addLibrarianButton;
    private javax.swing.JButton backButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField librarianAddressTextField;
    private javax.swing.JTextField librarianIdTextField;
    private javax.swing.JTextField librarianNameTextField;
    private javax.swing.JTextField librarianPhoneNumTextField;
    private javax.swing.JTextField passwordTextField;
    // End of variables declaration//GEN-END:variables
}
