/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package core.GUI;

import core.Library.Item;
import core.Library.Borrower;
import core.Library.Librarian;
import core.Library.Loan;
import core.Library.Reservation;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author krest
 */
public class Services extends javax.swing.JFrame
{
    
    DataAccessor.MySQLAccessor accessor;
    boolean firstRun = true;
    ArrayList <Item> itemsList;

    /**
     * Creates new form Services
     */
    public Services()
    {
        initComponents();
        accessor = new DataAccessor.MySQLAccessor();
        PopulateTables();
    }
    
    
    public void PopulateTables(){
        
        //Items Table
        itemsList = accessor.getItems();
        DefaultTableModel model = (DefaultTableModel)itemsTable.getModel();
        model.setRowCount(0);
        Object[] row = new Object[5];
        for(int i = 0; i<itemsList.size(); i++){
            row[0] = itemsList.get(i).getId();
            row[1] = itemsList.get(i).getTitle();
            row[2] = itemsList.get(i).getItemType();
            row[3] = itemsList.get(i).getCreator();
            row[4] = itemsList.get(i).getRentalDays();
            model.addRow(row);
        }
        
        //Borrowers Table
        ArrayList <Borrower> borrowersList =  accessor.GetBorrowerList();
        DefaultTableModel model2 = (DefaultTableModel)borrowerTable.getModel();
        Object[] row2 = new Object[4];
        for(int i = 0; i<borrowersList.size(); i++){
            row2[0] = borrowersList.get(i).getBorrowerId();
            row2[1] = borrowersList.get(i).getName();
            row2[2] = borrowersList.get(i).getAddress();
            row2[3] = borrowersList.get(i).getPhoneNum();
            model2.addRow(row2);
        }
        
        //Loan Table
        ArrayList <Loan> loanList =  accessor.getLoanList();
        DefaultTableModel model3 = (DefaultTableModel)loanTable.getModel();
        Object[] row3 = new Object[5];
        for(int i = 0; i<loanList.size(); i++){
            row3[0] = loanList.get(i).getLoanId();
            row3[1] = loanList.get(i).getItemId();
            row3[2] = loanList.get(i).getBorrowerId();
            row3[3] = loanList.get(i).getStartDate();
            row3[4] = loanList.get(i).getReturnDate();
            model3.addRow(row3);
        }
        
         //Reserve Table
        ArrayList <Reservation> reservationList =  accessor.getReservationList();
        DefaultTableModel model4 = (DefaultTableModel)reserveTable.getModel();
        Object[] row4 = new Object[4];
        for(int i = 0; i<reservationList.size(); i++){
            row4[0] = reservationList.get(i).getReserveID();
            row4[1] = reservationList.get(i).getItemID();
            row4[2] = reservationList.get(i).getBorrowerID();
            row4[3] = reservationList.get(i).getReservedDate();
            model4.addRow(row4);
        }
        
         //Reserve Table
        ArrayList <Librarian> librarianList =  accessor.getLibrarianList();
        DefaultTableModel model5 = (DefaultTableModel)librarianTable.getModel();
        Object[] row5 = new Object[5];
        for(int i = 0; i<librarianList.size(); i++){
            row5[0] = librarianList.get(i).getId();
            row5[1] = librarianList.get(i).getPassword();
            row5[2] = librarianList.get(i).getName();
            row5[3] = librarianList.get(i).getAddress();
            row5[4] = librarianList.get(i).getPhoneNum();
            model5.addRow(row5);
        }
        
        reserveTable.setDefaultEditor(Object.class, null);
        borrowerTable.setDefaultEditor(Object.class, null);
        loanTable.setDefaultEditor(Object.class, null);
        itemsTable.setDefaultEditor(Object.class, null);
        librarianTable.setDefaultEditor(Object.class, null);
    }
         
    private String getReserveIDFromTable(){
        int row = reserveTable.getSelectedRow();
        return String.valueOf(reserveTable.getValueAt(row, 0));
     }
     /**
     * Creates new form ViewBook
     * @throws java.sql.SQLException
     */
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        mainTabbedPane = new javax.swing.JTabbedPane();
        homePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        welcomeTextField = new javax.swing.JTextField();
        reserveButton = new javax.swing.JButton();
        registerLIbrarianButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        LoanButton1 = new javax.swing.JButton();
        enrolBorrowersButton1 = new javax.swing.JButton();
        itemsPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        itemsTable = new javax.swing.JTable();
        editItemButton = new javax.swing.JButton();
        addItemButton = new javax.swing.JButton();
        deleteItemButton = new javax.swing.JButton();
        deleteItemTextField = new javax.swing.JTextField();
        searchTextField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        clearSearchButtom = new javax.swing.JButton();
        borrowerPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        borrowerTable = new javax.swing.JTable();
        editBorrowerButton = new javax.swing.JButton();
        addBorrowerButton = new javax.swing.JButton();
        deleteBorrowerButton = new javax.swing.JButton();
        deleteBorrowerTextField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        loanTable = new javax.swing.JTable();
        returnItemsButton = new javax.swing.JButton();
        returnItemTextField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        reserveTable = new javax.swing.JTable();
        CancelButton = new javax.swing.JButton();
        cancelReservationTextField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        librarianTable = new javax.swing.JTable();
        addLibrarianButton = new javax.swing.JButton();
        deleteLibrarianButton = new javax.swing.JButton();
        editLibrarianButton = new javax.swing.JButton();
        deleteLibrarianTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainTabbedPane.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel1.setText("Welcome!");

        welcomeTextField.setBackground(new java.awt.Color(204, 204, 204));

        reserveButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        reserveButton.setText("Reserve Items");
        reserveButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        reserveButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                reserveButtonActionPerformed(evt);
            }
        });

        registerLIbrarianButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        registerLIbrarianButton.setText("Register Librarian");
        registerLIbrarianButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        registerLIbrarianButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                registerLIbrarianButtonActionPerformed(evt);
            }
        });

        backButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                backButtonActionPerformed(evt);
            }
        });

        LoanButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LoanButton1.setText("Loan Items");
        LoanButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LoanButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                LoanButton1ActionPerformed(evt);
            }
        });

        enrolBorrowersButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        enrolBorrowersButton1.setText("Enrol Borrowers");
        enrolBorrowersButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        enrolBorrowersButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                enrolBorrowersButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanelLayout.createSequentialGroup()
                        .addGap(0, 453, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(welcomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(homePanelLayout.createSequentialGroup()
                        .addComponent(backButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homePanelLayout.createSequentialGroup()
                        .addComponent(reserveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LoanButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(homePanelLayout.createSequentialGroup()
                        .addComponent(registerLIbrarianButton, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(enrolBorrowersButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(122, 122, 122))
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(welcomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(124, 124, 124)
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reserveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LoanButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerLIbrarianButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enrolBorrowersButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(backButton)
                .addContainerGap())
        );

        mainTabbedPane.addTab("Home", homePanel);

        itemsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Item Id", "Title", "Item Type", "Creator", "Rental Days"
            }
        ));
        jScrollPane1.setViewportView(itemsTable);

        editItemButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        editItemButton.setText("Edit");
        editItemButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        editItemButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                editItemButtonActionPerformed(evt);
            }
        });

        addItemButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addItemButton.setText("Add");
        addItemButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addItemButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                addItemButtonActionPerformed(evt);
            }
        });

        deleteItemButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deleteItemButton.setText("Delete");
        deleteItemButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        deleteItemButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                deleteItemButtonActionPerformed(evt);
            }
        });

        searchButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        searchButton.setText("Search");
        searchButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        searchButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                searchButtonActionPerformed(evt);
            }
        });

        clearSearchButtom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clearSearchButtom.setText("Clear Search");
        clearSearchButtom.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        clearSearchButtom.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                clearSearchButtomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout itemsPanelLayout = new javax.swing.GroupLayout(itemsPanel);
        itemsPanel.setLayout(itemsPanelLayout);
        itemsPanelLayout.setHorizontalGroup(
            itemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, itemsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(itemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(itemsPanelLayout.createSequentialGroup()
                        .addComponent(addItemButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(editItemButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addGroup(itemsPanelLayout.createSequentialGroup()
                        .addComponent(deleteItemTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(deleteItemButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(208, 208, 208))
            .addGroup(itemsPanelLayout.createSequentialGroup()
                .addGroup(itemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(itemsPanelLayout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(clearSearchButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(itemsPanelLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        itemsPanelLayout.setVerticalGroup(
            itemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemsPanelLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(itemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, itemsPanelLayout.createSequentialGroup()
                        .addGroup(itemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchButton)
                            .addComponent(clearSearchButtom))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, itemsPanelLayout.createSequentialGroup()
                        .addGroup(itemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deleteItemTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteItemButton))
                        .addGap(38, 38, 38)))
                .addGroup(itemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addItemButton)
                    .addComponent(editItemButton))
                .addGap(32, 32, 32))
        );

        mainTabbedPane.addTab("Items", itemsPanel);

        borrowerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Borrower Id", "Name", "Address", "Phone Number"
            }
        ));
        jScrollPane2.setViewportView(borrowerTable);

        editBorrowerButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        editBorrowerButton.setText("Edit");
        editBorrowerButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        editBorrowerButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                editBorrowerButtonActionPerformed(evt);
            }
        });

        addBorrowerButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addBorrowerButton.setText("Add");
        addBorrowerButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addBorrowerButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                addBorrowerButtonActionPerformed(evt);
            }
        });

        deleteBorrowerButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deleteBorrowerButton.setText("Delete");
        deleteBorrowerButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        deleteBorrowerButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                deleteBorrowerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout borrowerPanelLayout = new javax.swing.GroupLayout(borrowerPanel);
        borrowerPanel.setLayout(borrowerPanelLayout);
        borrowerPanelLayout.setHorizontalGroup(
            borrowerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borrowerPanelLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
            .addGroup(borrowerPanelLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(addBorrowerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(editBorrowerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, borrowerPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deleteBorrowerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(deleteBorrowerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(231, 231, 231))
        );
        borrowerPanelLayout.setVerticalGroup(
            borrowerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borrowerPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(borrowerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteBorrowerButton)
                    .addComponent(deleteBorrowerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(borrowerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBorrowerButton)
                    .addComponent(editBorrowerButton))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        mainTabbedPane.addTab("Borrowers", borrowerPanel);

        loanTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Loan Id", "Item Id", "Borrower Id", "Start Date", "Return Date"
            }
        ));
        jScrollPane3.setViewportView(loanTable);

        returnItemsButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        returnItemsButton.setText("Return Items");
        returnItemsButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        returnItemsButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                returnItemsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(returnItemTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(returnItemsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(169, 169, 169))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(returnItemsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returnItemTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        mainTabbedPane.addTab("Loaned Items", jPanel1);

        reserveTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Reserve Id", "Item Id", "Borrower Id", "Reserve Date"
            }
        ));
        jScrollPane4.setViewportView(reserveTable);

        CancelButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CancelButton.setText("Cancel Reservation");
        CancelButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CancelButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                CancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(cancelReservationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(200, 200, 200))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelReservationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(103, Short.MAX_VALUE))
        );

        mainTabbedPane.addTab("Reserved Items", jPanel2);

        librarianTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Librarian Id", "Password", "Name", "Address", "Phone Number"
            }
        ));
        jScrollPane5.setViewportView(librarianTable);

        addLibrarianButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addLibrarianButton.setText("Add");
        addLibrarianButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addLibrarianButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                addLibrarianButtonActionPerformed(evt);
            }
        });

        deleteLibrarianButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deleteLibrarianButton.setText("Delete");
        deleteLibrarianButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        deleteLibrarianButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                deleteLibrarianButtonActionPerformed(evt);
            }
        });

        editLibrarianButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        editLibrarianButton.setText("Edit");
        editLibrarianButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        editLibrarianButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                editLibrarianButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(deleteLibrarianTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(addLibrarianButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(deleteLibrarianButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(222, 222, 222))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(editLibrarianButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(133, 133, 133))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteLibrarianButton)
                    .addComponent(deleteLibrarianTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editLibrarianButton)
                    .addComponent(addLibrarianButton))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        mainTabbedPane.addTab("Librarians", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(mainTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(mainTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_backButtonActionPerformed
    {//GEN-HEADEREND:event_backButtonActionPerformed
        dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void reserveButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_reserveButtonActionPerformed
    {//GEN-HEADEREND:event_reserveButtonActionPerformed
        this.dispose();
        new reserveItems().setVisible(true);
    }//GEN-LAST:event_reserveButtonActionPerformed

    private void registerLIbrarianButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_registerLIbrarianButtonActionPerformed
    {//GEN-HEADEREND:event_registerLIbrarianButtonActionPerformed
        this.dispose();
        new addLibrarian(false, null).setVisible(true);
    }//GEN-LAST:event_registerLIbrarianButtonActionPerformed

    private void LoanButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_LoanButton1ActionPerformed
    {//GEN-HEADEREND:event_LoanButton1ActionPerformed
        this.dispose();
        new LoanItem().setVisible(true);
    }//GEN-LAST:event_LoanButton1ActionPerformed

    private void addItemButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_addItemButtonActionPerformed
    {//GEN-HEADEREND:event_addItemButtonActionPerformed
        this.dispose();
        new addItem(false, null).setVisible(true);
    }//GEN-LAST:event_addItemButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_CancelButtonActionPerformed
    {//GEN-HEADEREND:event_CancelButtonActionPerformed
        String reserveId = cancelReservationTextField.getText();
        
        if (reserveId.isEmpty())
        { 
            JOptionPane.showMessageDialog(null, "Please Enter a Valid reserve Id.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        accessor.cancelReservation(reserveId);
        this.dispose();
        new Services().setVisible(true);
        
        JOptionPane.showMessageDialog(null, "The reservation is successfully cancelled!", "Alert", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void deleteItemButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_deleteItemButtonActionPerformed
    {//GEN-HEADEREND:event_deleteItemButtonActionPerformed
        String itemId = deleteItemTextField.getText();
        
        if (itemId.isEmpty())
        { 
            JOptionPane.showMessageDialog(null, "Please Enter a Valid item Id.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        accessor.deleteItem(itemId);
        this.dispose();
        new Services().setVisible(true);
        
        JOptionPane.showMessageDialog(null, "The item is successfully deleted!", "Alert", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_deleteItemButtonActionPerformed

    private void returnItemsButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_returnItemsButtonActionPerformed
    {//GEN-HEADEREND:event_returnItemsButtonActionPerformed
        String loanId = returnItemTextField.getText();
        accessor.returnItemOnLoan(loanId);
        this.dispose();
        new Services().setVisible(true);
        
        JOptionPane.showMessageDialog(null, "The item is successfully returned!", "Alert", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_returnItemsButtonActionPerformed

    private void editItemButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_editItemButtonActionPerformed
    {//GEN-HEADEREND:event_editItemButtonActionPerformed
        // TODO add your handling code here:
        if (!isItemSelected()){
                    JOptionPane.showMessageDialog(null, "Please select an Item to edit.", "Can not Edit", JOptionPane.INFORMATION_MESSAGE);
                    return;
        }
        
        this.dispose();
        new addItem(true, getItemFromTable()).setVisible(true);
    }//GEN-LAST:event_editItemButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_searchButtonActionPerformed
    {//GEN-HEADEREND:event_searchButtonActionPerformed
        // TODO add your handling code here:
        
        if (searchTextField.getText().matches("")){
            PopulateTables();
            return;
        }
        
       ArrayList <Item> newList = new ArrayList <Item>();
       for (int i = 0; i < itemsTable.getRowCount(); i++) {
         for (int j = 0; j < itemsTable.getColumnCount(); j++) {
             Object o = itemsTable.getValueAt(i, j);
                 if (o instanceof String) {
                   if (((String) o).indexOf(searchTextField.getText()) != -1){
                       if(!newList.contains(itemsList.get(i))){
                           newList.add(itemsList.get(i));
                       }
                       
                   }
                }else if (o instanceof Item.ItemType){
                    String itemTypeString = getStringForItemType((Item.ItemType) o);
                     if (itemTypeString.indexOf(searchTextField.getText()) != -1){
                       if(!newList.contains(itemsList.get(i))){
                           newList.add(itemsList.get(i));
                       }
                   }
                 }
            }
          }
        DefaultTableModel model = (DefaultTableModel)itemsTable.getModel();
        model.setRowCount(0);
        Object[] row = new Object[5];
        for(int i = 0; i<newList.size(); i++){
            row[0] = newList.get(i).getId();
            row[1] = newList.get(i).getTitle();
            row[2] = newList.get(i).getItemType();
            row[3] = newList.get(i).getCreator();
            row[4] = newList.get(i).getRentalDays();
            model.addRow(row);
        }
    }//GEN-LAST:event_searchButtonActionPerformed

     public String getStringForItemType(Item.ItemType type){
        switch (type){
            case Book:
                return "Book";
            case DVD:
                return "DVD";
            case Magazine:
                return "Magazine";
            default:
                return  "Book"; //book because this is most common
        }
    }
    
    
    
    
    private void clearSearchButtomActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_clearSearchButtomActionPerformed
    {//GEN-HEADEREND:event_clearSearchButtomActionPerformed
        // TODO add your handling code here:
        PopulateTables();
        searchTextField.setText("");
    }//GEN-LAST:event_clearSearchButtomActionPerformed

    private void enrolBorrowersButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_enrolBorrowersButton1ActionPerformed
    {//GEN-HEADEREND:event_enrolBorrowersButton1ActionPerformed
        this.dispose();
        new EnrolBorrower(false, null).setVisible(true);
    }//GEN-LAST:event_enrolBorrowersButton1ActionPerformed

    private void addBorrowerButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_addBorrowerButtonActionPerformed
    {//GEN-HEADEREND:event_addBorrowerButtonActionPerformed
        this.dispose();
        new EnrolBorrower(false, null).setVisible(true);
    }//GEN-LAST:event_addBorrowerButtonActionPerformed

    private void addLibrarianButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_addLibrarianButtonActionPerformed
    {//GEN-HEADEREND:event_addLibrarianButtonActionPerformed
       this.dispose();
       new addLibrarian(false, null).setVisible(true);
    }//GEN-LAST:event_addLibrarianButtonActionPerformed

    private void deleteBorrowerButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_deleteBorrowerButtonActionPerformed
    {//GEN-HEADEREND:event_deleteBorrowerButtonActionPerformed
        String borrowerId = deleteBorrowerTextField.getText();
        
        if (borrowerId.isEmpty())
        { 
            JOptionPane.showMessageDialog(null, "Please Enter a Valid borrower Id.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        accessor.deleteBorrower(borrowerId);
        this.dispose();
        new Services().setVisible(true);
        
        JOptionPane.showMessageDialog(null, "The selected borrower is successfully deleted!", "Alert", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_deleteBorrowerButtonActionPerformed

    private void deleteLibrarianButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_deleteLibrarianButtonActionPerformed
    {//GEN-HEADEREND:event_deleteLibrarianButtonActionPerformed
        String librarianId = deleteLibrarianTextField.getText();
        
        if (librarianId.isEmpty())
        { 
            JOptionPane.showMessageDialog(null, "Please Enter a Valid Librarian Id.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        accessor.deleteLibrarian(librarianId);
        this.dispose();
        new Services().setVisible(true);
        
        JOptionPane.showMessageDialog(null, "The selected Librarian is successfully deleted!", "Alert", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_deleteLibrarianButtonActionPerformed

    private void editBorrowerButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_editBorrowerButtonActionPerformed
    {//GEN-HEADEREND:event_editBorrowerButtonActionPerformed
         if (!isItemSelected()){
                    JOptionPane.showMessageDialog(null, "Please select a borrower to edit.", "Invalid Action", JOptionPane.INFORMATION_MESSAGE);
                    return;
        }
        this.dispose();
        new EnrolBorrower(true, getBorrowerFromTable()).setVisible(true);
    }//GEN-LAST:event_editBorrowerButtonActionPerformed

    private void editLibrarianButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_editLibrarianButtonActionPerformed
    {//GEN-HEADEREND:event_editLibrarianButtonActionPerformed
        if (!isItemSelected()){
                    JOptionPane.showMessageDialog(null, "Please select a librarian to edit.", "Invalid Action", JOptionPane.INFORMATION_MESSAGE);
                    return;
        }
        this.dispose();
        new addLibrarian(true, getLibrarianFromTable()).setVisible(true);
    }//GEN-LAST:event_editLibrarianButtonActionPerformed

    private Item getItemFromTable(){
        Item i = new Item();
        int row = itemsTable.getSelectedRow();
        i.setId(String.valueOf(itemsTable.getValueAt(row, 0)));
        i.setTitle(String.valueOf(itemsTable.getValueAt(row, 1)));
        i.setItemType(getItemTypeForSelectedRow());
        i.setCreator(String.valueOf(itemsTable.getValueAt(row, 3)));
        return i;
    }
    
    public Item.ItemType getItemTypeForSelectedRow(){
        int row = itemsTable.getSelectedRow();
        switch (String.valueOf(itemsTable.getValueAt(row, 2))){
            case "Book":
                return Item.ItemType.Book;
            case "DVD":
                return Item.ItemType.DVD;
            case "Magazine":
                return Item.ItemType.Magazine;
            default:
                return Item.ItemType.Book; //book because this is most common
        }
    }
    
    private Borrower getBorrowerFromTable(){
        Borrower b = new Borrower();
        int row = borrowerTable.getSelectedRow();
        b.setBorrowerId(String.valueOf(borrowerTable.getValueAt(row, 0)));
        b.setName(String.valueOf(borrowerTable.getValueAt(row, 1)));
        b.setAddress(String.valueOf(borrowerTable.getValueAt(row, 2)));
        b.setPhoneNum(String.valueOf(borrowerTable.getValueAt(row, 3)));
        return b;
    }
    
    private Librarian getLibrarianFromTable(){
        Librarian l = new Librarian();
        int row = librarianTable.getSelectedRow();
        l.setId(String.valueOf(librarianTable.getValueAt(row, 0)));
        l.setPassword(String.valueOf(librarianTable.getValueAt(row, 1)));
        l.setName(String.valueOf(librarianTable.getValueAt(row, 2)));
        l.setAddress(String.valueOf(librarianTable.getValueAt(row, 3)));
        l.setPhoneNum(String.valueOf(librarianTable.getValueAt(row, 4)));
        return l;
    }
    
    private boolean isItemSelected(){
       if( itemsTable.getSelectedRowCount() == 0){
           return false;
       }else{
           return true;
       }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Services.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Services.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Services.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Services.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Services().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JButton LoanButton1;
    private javax.swing.JButton addBorrowerButton;
    private javax.swing.JButton addItemButton;
    private javax.swing.JButton addLibrarianButton;
    private javax.swing.JButton backButton;
    private javax.swing.JPanel borrowerPanel;
    private javax.swing.JTable borrowerTable;
    private javax.swing.JTextField cancelReservationTextField;
    private javax.swing.JButton clearSearchButtom;
    private javax.swing.JButton deleteBorrowerButton;
    private javax.swing.JTextField deleteBorrowerTextField;
    private javax.swing.JButton deleteItemButton;
    private javax.swing.JTextField deleteItemTextField;
    private javax.swing.JButton deleteLibrarianButton;
    private javax.swing.JTextField deleteLibrarianTextField;
    private javax.swing.JButton editBorrowerButton;
    private javax.swing.JButton editItemButton;
    private javax.swing.JButton editLibrarianButton;
    private javax.swing.JButton enrolBorrowersButton1;
    private javax.swing.JPanel homePanel;
    private javax.swing.JPanel itemsPanel;
    private javax.swing.JTable itemsTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable librarianTable;
    private javax.swing.JTable loanTable;
    private javax.swing.JTabbedPane mainTabbedPane;
    private javax.swing.JButton registerLIbrarianButton;
    private javax.swing.JButton reserveButton;
    private javax.swing.JTable reserveTable;
    private javax.swing.JTextField returnItemTextField;
    private javax.swing.JButton returnItemsButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JTextField welcomeTextField;
    // End of variables declaration//GEN-END:variables

   
}
